
import HeaderTop from "../components/HeaderTop";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderMain from "../components/HeaderMain";
import Navbar from "../components/Navbar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobNavbar from "../components/MobNavbar";
import Footer from "../components/Footer";
import Cookies from "js-cookie";
import {useEffect} from 'react'

import "bootstrap/dist/css/bootstrap.min.css";
import Router  from "next/router";

export const metadata: Metadata = {
  title: "Almari",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {

  const user = Cookies.get('user');

  useEffect(() => {
    isCookieExit()
  }, [])

const isCookieExit = async () => {
  const username=Cookies.get('user');

  if(!username)
  {
    Router.push('/Login');
  }
}

  return (
    
    <main>
      <HeaderTop />
      <HeaderMain user={user}/>
      <Navbar />
      <MobNavbar />
      {children}
      <Footer />
      <ToastContainer />
    </main>
  );
}
